# Generated by Django 2.1.5 on 2019-01-31 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Контакт')),
                ('link', models.CharField(max_length=128, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='TypeContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Нименование класса')),
                ('eng_name', models.CharField(max_length=32, verbose_name='Псевдоним на английском')),
            ],
            options={
                'verbose_name': 'Тип контакта',
                'verbose_name_plural': 'Тип контактов',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.TypeContact', verbose_name='Тип контакта'),
        ),
    ]
