# Generated by Django 2.1.5 on 2019-02-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0006_auto_20190211_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, max_length=1024, verbose_name='Комментарий')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='services.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
            },
        ),
    ]
