# Generated by Django 2.1.5 on 2019-01-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Наименование услуги')),
                ('description', models.TextField(max_length=512, verbose_name='Краткое описание')),
                ('min_price', models.FloatField(verbose_name='Минимальная стоимость')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceCategory', verbose_name='Категория услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование пункта')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Пункт работы',
                'verbose_name_plural': 'Пункты работ',
            },
        ),
    ]
