# Generated by Django 2.1.5 on 2019-01-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_workitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.Service', verbose_name='Услуга'),
        ),
    ]
