# Generated by Django 2.1.5 on 2019-01-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190118_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='url_link',
            field=models.CharField(default='uslugi', max_length=32, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.ServiceCategory', verbose_name='Категория услуги'),
        ),
    ]
