# Generated by Django 2.1.5 on 2019-01-31 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190120_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='note',
            field=models.TextField(default=django.utils.timezone.now, max_length=1024, verbose_name='Замечание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='warn',
            field=models.TextField(default=django.utils.timezone.now, max_length=1024, verbose_name='Предупреждение'),
            preserve_default=False,
        ),
    ]
