# Generated by Django 2.1.5 on 2019-02-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190131_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=512, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_price',
            field=models.CharField(max_length=32, verbose_name='Минимальная стоимость'),
        ),
        migrations.AlterField(
            model_name='service',
            name='note',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Замечание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='warn',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Предупреждение'),
        ),
    ]
