# Generated by Django 2.1.5 on 2019-01-22 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsrelationship',
            options={'verbose_name': 'Читайте также', 'verbose_name_plural': 'Читайте также'},
        ),
        migrations.AlterField(
            model_name='newsrelationship',
            name='to_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_news', to='news.News', verbose_name='Новость'),
        ),
    ]
