# Generated by Django 2.1.5 on 2019-01-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190122_1243'),
        ('news', '0002_auto_20190122_1154'),
        ('news', '0002_auto_20190121_2314'),
    ]

    operations = [
    ]
