# Generated by Django 2.1.5 on 2019-01-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Компания')),
                ('subt', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='Год написания')),
                ('url', models.ImageField(blank=True, upload_to='images/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекоментации',
                'ordering': ['subt', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
