# Generated by Django 2.1.5 on 2019-01-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190119_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['year', 'company'], 'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекоментации'},
        ),
    ]
