# Generated by Django 2.1.5 on 2019-01-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover_image',
            new_name='picture',
        ),
    ]
