# Generated by Django 2.1.5 on 2019-01-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование сертификата')),
                ('company', models.CharField(max_length=64, verbose_name='Наименование компании')),
                ('image', models.ImageField(blank=True, upload_to='certificates/', verbose_name='Изоражение')),
            ],
        ),
    ]
