# Generated by Django 2.1.5 on 2019-02-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=64, verbose_name='Название акции')),
                ('preview', models.TextField(max_length=1024, verbose_name='Анонс')),
                ('text', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
