# Generated by Django 2.1.5 on 2019-01-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advice',
            options={'verbose_name': 'Полезный совет', 'verbose_name_plural': 'Полезные советы'},
        ),
        migrations.AlterField(
            model_name='advice',
            name='text',
            field=models.TextField(verbose_name='Содержание совета'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Заголовок совета'),
        ),
    ]
