# Generated by Django 2.1.5 on 2019-01-22 02:58

from django.db import migrations, models
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advices', '0002_auto_20190122_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='link',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='text',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Заголовок'),
        ),
    ]
