# Generated by Django 2.1.5 on 2019-01-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=140, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, upload_to='images/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['id'],
            },
        ),
    ]
